In [3]:
from sklearn import datasets  
#導入內置資料集模組                      
from sklearn.neighbors import KNeighborsClassifier 
#導入sklearn.neighbors模組中KNN類
import numpy as np 
np.random.seed(0)  
#設置隨機種子，不設置的話預設是按系統時間作為參數，因此每次調用隨機模組時產生的亂數都不一樣設置後每次產生的一樣
iris=datasets.load_iris() 
#導入鳶尾花的資料集，iris是一個類似於結構體的東西，內部有樣本資料，如果是監督學習還有標籤資料

In [4]:
iris_x=iris.data   
 #樣本資料150*4二維資料，代表150個樣本，每個樣本4個屬性分別為花瓣和花萼的長、寬
iris_y=iris.target  
#長150的以為陣列，樣本資料的標籤
indices = np.random.permutation(len(iris_x)) 
#permutation接收一個數作為參數(150),產生一個0-149一維陣列，只不過是隨機打亂的，當然她也可以接收一個一維陣列作為參數，結果是直接對這個陣列打亂
iris_x_train = iris_x[indices[:-10]]
 #隨機選取140個樣本作為訓練資料集
iris_y_train = iris_y[indices[:-10]] 
#並且選取這140個樣本的標籤作為訓練資料集的標籤
iris_x_test  = iris_x[indices[-10:]]
 #剩下的10個樣本作為測試資料集
iris_y_test  = iris_y[indices[-10:]] 
#並且把剩下10個樣本對應標籤作為測試資料及的標籤



In [7]:
knn = KNeighborsClassifier() 
#定義一個knn分類器物件
knn.fit(iris_x_train, iris_y_train)  
#調用該對象的訓練方法，主要接收兩個參數：訓練資料集及其樣本標籤

iris_y_predict = knn.predict(iris_x_test) 
 #調用該物件的測試方法，主要接收一個參數：測試資料集
probility=knn.predict_proba(iris_x_test)  
 #計算各測試樣本基於概率的預測
neighborpoint=knn.kneighbors(iris_x_test,5,False)
#計算與最後一個測試樣本距離在最近的5個點，返回的是這些樣本的序號組成的陣列
score=knn.score(iris_x_test,iris_y_test,sample_weight=None)
#調用該物件的打分方法，計算出準確率

print('iris_y_predict = ')  
print(iris_y_predict)  
#輸出測試的結果

print('iris_y_test = ')
print(iris_y_test)    
#輸出原始測試資料集的正確標籤，以方便對比
print('Accuracy:',score) 
#輸出準確率計算結果
print('neighborpoint of last test sample:',neighborpoint)
 
print('probility:',probility)


iris_y_predict = 
[1 2 1 0 0 0 2 1 2 0]
iris_y_test = 
[1 1 1 0 0 0 2 1 2 0]
Accuracy: 0.9
neighborpoint of last test sample: [[ 71  81 127  63  38]
 [119  33  76  60  52]
 [ 79 132   1  13  27]
 [ 44 113 107  68  32]
 [122  87  99  97  68]
 [106  15  93  61  82]
 [ 46  30  86  70  34]
 [ 39 128 127  50  63]
 [116 104  80  51 121]
 [ 75  41  96  78 123]]
probility: [[0.  1.  0. ]
 [0.  0.4 0.6]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]]
